### ISSUE TITLE
missing word in README

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#2]
<img width="860" alt="screen shot 2017-11-17 at 1 46 25 pm" src="https://user-images.githubusercontent.com/28125427/32963387-c97360ce-cb9d-11e7-9bae-447c1838809c.png">

Likely words: "response", "repo list", etc.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue, @logemerson! 

We've updated the materials to fix the issue.

Hope you are doing well, my friend!
