### ISSUE TITLE
FYI -- Seems like content is missing or was accidentally deleted

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#4]
Issue : There seems to be something missing between the below two paragraphs. Where "full" cuts off unexpectedly.

Location in Lesson : "When we add the event listener to our req object, we set it up so that this will be our req object  inside our callback function. So, inside showRepositories, we can access this.responseText to see the full [<<-- RIGHT HERE!]

Now that we know how to access the response, let's do something with it."

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @raiet13.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
