### ISSUE TITLE
Portion of text missing in readme

### ISSUE THREAD

**Issue by denisepen** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#5]
The following line is never completed in this reading: 

_When we add the event listener to our req object, we set it up so that this will be our req object inside our callback function. So, inside showRepositories, we can access this.responseText to see the full_

Now that we know how to access the response, let's do something with it.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @denisepen.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
