### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by maxwellbenton** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#7]
In v6, this lesson is the first async JS lesson students see, but doesn't clearly introduce JSON or APIs, but is our main code along lesson for XHR.

Proposal for v7:
Move existing, newer content js-async-fetch-readme and js-async-weather-api-lab to be new intro to async JS, with this lesson being the third in the section.  wip-rewrite-v7-mb is an updated version which removes some intro content and would work better as the third lesson on async.

Should resolve #3 and #6 

wip-solution is a new solution branch for this code along based on wip-rewrite-v7-mb

**Comment by drakeltheryuujin** [comment]
Accepted and merged in.
